spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://postgres-db-master:5432/postgres
    username: admin
    password: "1357"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
